### ISSUE TITLE
Problem on GoogleWebView not present.

### ISSUE THREAD

**Issue by hebeguess** [PeterCxy/WebViewGoogle#1]
Keep in mind that many user will likely mistakenly activate this module before even install GoogleWebView from Google Play.

Since webview is such a crucial component on Android and typically cannot run properly without it.
Android will still boot, however crash will be endless on system that fail to load a proper webview package during boot.

My suggestions is put some words on xposed module descriptions to warns users to install GoogleWebview beforehand. Alternatively, add auto-detection mechanism on this module to prevent it from happening.

**Comment by PeterCxy** [comment]
Thank you, added to Xposed page first line.
